---
abstract: 'Use time-stamp from Git instead of process start time.'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  Dist::Zilla::Util::Test::KENTNL: '1.003001'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Git::Wrapper::Plus::Support: '0'
  Git::Wrapper::Plus::Tester: '0'
  Test::DZil: '0'
  Test::Fatal: '0'
  Test::More: '0'
  perl: '5.008'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.008'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.008, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-Git-NextRelease
provides:
  Dist::Zilla::Plugin::Git::NextRelease:
    file: lib/Dist/Zilla/Plugin/Git/NextRelease.pm
    version: '0.004002'
recommends:
  Moose: '2.000'
requires:
  DateTime: '0'
  Dist::Zilla: '5.000'
  Dist::Zilla::Plugin::NextRelease: '0'
  Dist::Zilla::Util::ConfigDumper: '0'
  Git::Wrapper::Plus: '0.003100'
  Moose: '0'
  String::Formatter: '0.100680'
  perl: '5.008'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/Dist-Zilla-Plugin-Git-NextRelease/issues
  homepage: https://github.com/kentnl/Dist-Zilla-Plugin-Git-NextRelease
  repository: https://github.com/kentnl/Dist-Zilla-Plugin-Git-NextRelease.git
version: '0.004002'
